routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\QuizController;
use App\Http\Controllers\Admin\QuestionController;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    Route::group(['middleware' => ['role:Admin'], 'prefix' => 'admin'], function () {
        Route::resource('questions', QuestionController::class);
        Route::get('users', [UserController::class, 'index'])->name('users');
    });

    Route::group(['middleware' => ['role:User'], 'prefix' => 'user'], function () {
        Route::resource('quiz', QuizController::class);
        Route::post('quiz/start', [QuizController::class, 'start'])->name('quiz.start');
    });
});



require __DIR__.'/auth.php';

app/Models/Question.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Question extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'name'
    ];

    public function options(){
        return $this->hasMany(Option::class, 'question_id', 'id');
    }
}

app/Http/Controllers/API/V1/QuestionController.php
<?php

namespace App\Http\Controllers\API\V1;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Question;
use App\Models\AnswerLog;
use App\Models\Option;
use App\Models\Answer;
use Auth;
use Carbon\Carbon;

class QuestionController extends Controller
{
    public function getQuestions(Request $request){
        $answerLog = Auth::user()->answerLog;
        $questionDB = Question::with('options')->get()->toArray();

        $responseArr = [
            'questions' => $questionDB,
            'answerLog' => $answerLog
        ];

        return response()->json([
            'success' => 1,
            'message' => 'Success',
            'data' => $responseArr
        ]);
    }

    public function startQuiz(Request $request){
        $answerLog = Auth::user()->answerLog;
        if($answerLog){
            if(!is_null($answerLog->ended_at)){
                return response()->json([
                    'success' => 0,
                    'message' => 'You have already attempt this quiz',
                    'data' => []
                ]);
            }
            return response()->json([
                'success' => 0,
                'message' => 'Quiz already started',
                'data' => []
            ]);
        } else{
            AnswerLog::create([
                'user_id' => Auth::user()->id,
                'started_at' => Carbon::now()
            ]);
        }

        return response()->json([
            'success' => 1,
            'message' => 'Quiz started successfully.',
            'data' => []
        ]);
    }

    public function submitQuiz(Request $request){
        try{
            $answerLog = Auth::user()->answerLog;
            if($answerLog){
                if(!is_null($answerLog->ended_at)){
                    return response()->json([
                        'success' => 0,
                        'message' => 'You have already attempt this quiz',
                        'data' => []
                    ]);
                }

                foreach($request->answer as $key => $answer){
                    $question = Question::with(['options' => function($query){
                        return $query->where('is_correct','1');
                    }])
                    ->where('id', $key)->first();
        
                    $option = Option::find($answer);
        
                    $data = [
                        'question_id' => $key,
                        'option_id' => $answer,
                        'user_id' => Auth::user()->id,
                        'question_name' => $question->name,
                        'option_name' => $option->option,
                        'is_correct' =>($question->options[0]->id == $answer) ? '1' : '0'
                    ];
        
                    $answer = Answer::updateOrCreate(['question_id' => $key, 'user_id' => Auth::user()->id], $data);
                }

                $totalCorrectAnswers = Answer::where('user_id', Auth::user()->id)->where('is_correct', '1')->count();
                $answerLog = AnswerLog::where('user_id', Auth::user()->id)->first();
                $answerLog->ended_at = Carbon::now();
                $answerLog->save();
        
                $startDate = $answerLog->started_at;
                $endDate = $answerLog->ended_at;
                $diffInMinutes = $endDate->diffInMinutes($startDate);
        
                $responseArr = [
                    'minutes' => $diffInMinutes,
                    'correctAnswer' => $totalCorrectAnswers
                ];
                return response()->json([
                    'success' => 1,
                    'message' => 'Quiz submitted successfully.',
                    'data' => $responseArr
                ]);

            } else{
                return response()->json([
                    'success' => 0,
                    'message' => 'Something went wrong',
                    'data' => []
                ]);
            }
        } catch (\Exception $e) {
            return response()->json([
                'success' => 0,
                'message' => $e->getMessage(),
                'data' => []
            ]);
        }
    }
}

app/Http/Controllers/Admin/QuestionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\StoreQuestionRequest;
use App\Models\Question;
use App\Models\Option;
use DB;

class QuestionController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $questionDB = Question::orderBy('id','desc')->get();

        return view('admin.questions.index', compact('questionDB'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $options = ['option1','option2','option3','option4'];
        return view('admin.questions.create', compact('options'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreQuestionRequest $request)
    {
        //dd($request->all());
        DB::beginTransaction();
        try{
            $questionDB = Question::create(['name' => $request->name]);
            foreach($request->options as $key => $option){
                $optionData = [
                    'question_id' => $questionDB->id,
                    'option' => $option,
                    'is_correct' => ($key == $request->is_correct) ? '1' :'0'
                ];
    
                Option::create($optionData);

                DB::commit();
            }

            return redirect()->route('questions.index')->with('success', 'Question added successfully.');
        } catch (\Exception $e) {
            DB::rollback();
            return redirect()->route('questions.create')->with('danger', 'Somethin went wrong. Please try again.');
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $questionDB = Question::with('options')->findOrFail($id);
        return view('admin.questions.edit', compact('questionDB'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(StoreQuestionRequest $request, string $id)
    {
        DB::beginTransaction();
        try{
            $questionDB = Question::updateOrCreate(['id'=>$id],['name' => $request->name]);
            foreach($request->options as $key => $option){
                $optionData = [
                    'option' => $option,
                    'is_correct' => ($key == $request->is_correct) ? '1' :'0'
                ];
    
                Option::updateOrCreate(['id' => $key], $optionData);

                DB::commit();
            }

            return redirect()->route('questions.index')->with('success', 'Question updated successfully.');
        } catch (\Exception $e) {
            DB::rollback();
            return back()->with('danger', 'Somethin went wrong. Please try again.');
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $questionDB = Question::findOrFail($id);
        $questionDB->delete();
        return redirect()->route('questions.index')->with('success', 'Question deleted successfully.');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/admin/questions/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    <div class="flash-message">
                        @if($errors)
                            @foreach($errors->all() as $error)
                                <div class="text-danger">{{$error}}</div>
                            @endforeach
                        @endif
                        @foreach (['danger', 'warning', 'success', 'info'] as $msg)
                          @if(Session::has($msg))
                          <p class="alert alert-{{ $msg }}">{{ Session::get($msg) }}</p>
                          @endif
                        @endforeach
                      </div>

                    <form id="question-form" method="POST" action="{{route('questions.store')}}">
                        @csrf
                        <div class="form-group">
                          <label for="exampleFormControlInput1">Question Name</label>
                          <input type="name" class="form-control" id="name" name='name' placeholder="Question">
                        </div>
                        <br>
                        @foreach($options as $key => $option)
                            <div class="form-group mb-2">
                                <label for="">Option{{$loop->iteration}}</label>
                                <div class="row">
                                    <div class="col-md-8">
                                        <input type="name" class="form-control" name="options[{{$key}}]" placeholder="Option{{$loop->iteration}}">
                                    </div>
                                    <div class="col-md-4">
                                        <input type="radio" name="is_correct" value="{{$key}}" > Correct
                                    </div>
                                </div>
                            </div>
                            @endforeach
                            <div class="form-group mb-2 mt-2">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {!! JsValidator::formRequest('App\Http\Requests\StoreQuestionRequest', '#question-form') !!}
</x-app-layout>

resources/views/admin/questions/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    <div class="flash-message">
                        @if($errors)
                            @foreach($errors->all() as $error)
                                <div class="text-danger">{{$error}}</div>
                            @endforeach
                        @endif
                        @foreach (['danger', 'warning', 'success', 'info'] as $msg)
                          @if(Session::has($msg))
                          <p class="alert alert-{{ $msg }}">{{ Session::get($msg) }}</p>
                          @endif
                        @endforeach
                      </div>
                      
                    <form id="question-form" method="POST" action="{{route('questions.update', $questionDB->id)}}">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                          <label for="exampleFormControlInput1">Question Name</label>
                          <input type="name" class="form-control" id="name" name='name' value="{{$questionDB->name}}" placeholder="Question">
                        </div>
                        <br>
                        @foreach($questionDB->options as $key => $option)
                       
                            <div class="form-group mb-2">
                                <label for="">Option{{$loop->iteration}}</label>
                                <div class="row">
                                    <div class="col-md-8">
                                        <input type="name" class="form-control" name="options[{{$option->id}}]" placeholder="Option{{$loop->iteration}}" value="{{$option->option}}">
                                    </div>
                                    <div class="col-md-4">
                                        <input type="radio" name="is_correct" value="{{$option->id}}" {{($option->is_correct) ? 'checked' :''}}> Correct
                                    </div>
                                </div>
                            </div>
                            @endforeach
                            <div class="form-group mb-2 mt-2">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {!! JsValidator::formRequest('App\Http\Requests\StoreQuestionRequest', '#question-form') !!}
</x-app-layout>

resources/views/admin/questions/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    <div class="flash-message">
                        @foreach (['danger', 'warning', 'success', 'info'] as $msg)
                          @if(Session::has($msg))
                          <p class="alert alert-{{ $msg }}">{{ Session::get($msg) }}</p>
                          @endif
                        @endforeach
                      </div>
                    <div class="text-right mb-1">
                        <a href="{{route('questions.create')}}" class="btn btn-primary ">Add Question</a>
                    </div>
                    <table class="table">
                        <thead class="table-dark">
                          <tr>
                            <th scope="col">#</th>
                            <th scope="col">Question</th>
                            <th scope="col">Options</th>
                            <th scope="col">Action</th>
                          </tr>
                        </thead>
                        <tbody>
                            @foreach($questionDB as $question)
                                <tr>
                                    <th scope="row">{{$question->id}}</th>
                                    <td>{{$question->name}}</td>
                                    <td>
                                        <ul>
                                        @foreach($question->options as $option)
                                        <li>{{$loop->iteration." - ".$option->option}}</li>
                                        @endforeach
                                        </ul>
                                    </td>
                                    <td>
                                        <a href="{{route('questions.edit',$question->id)}}" class="btn btn-primary btn-sm">Edit</a>

                                        <form action="{{route('questions.destroy', $question->id)}}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                      </table>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>